### PR TITLE
Update de.json

### PR DESCRIPTION
**Pull request by rtkohl**
Updated the digestConfigured value

### CODE REVIEW

**Comment by RomanJRW** [comment]
Did this cause a problem @rtkohl? We would also need to update it in the Optimize repo if so

**Comment by rtkohl** [comment]
Yes it did cause an error:

image-2023-03-22-10-02-59-326

**Review by RomanJRW — APPROVED** [review]
Nice catch, thanks 👍

**Comment by RomanJRW** [comment]
Will fix in the Optimize repo too with https://github.com/camunda/camunda-optimize/pull/6230

**Pull request merged**
